source 'https://rubygems.org'

gem 'thin'
gem 'sinatra'
gem 'sinatra-websocket'
gem 'sinatra-contrib'
gem 'octokit'
gem 'slim'
gem 'pry'
gem 'rake'
gem 'awesome_print'
gem 'redis'
gem 'redis-queue'
gem 'em-hiredis'
gem 'activesupport'
gem 'sprockets'
# gem 'sprockets-helpers'
gem 'sass'
gem 'uglifier'
# gem 'sinatra-formhelpers-ng'
